Repository abhisek247767/LeetCode2024-6Companies30Days, pull requests merged in 2024-10, with the labels that each got.

#14 update README.md
  README.md
Labels: Hacktoberfest-Accepted

#15 Create compoundInterest.cpp
  compoundInterest.cpp
Labels: Hacktoberfest-Accepted

#19 added SortColors cpp file
  C++/SortColors.CPP
Labels: Hacktoberfest-Accepted

#18 Create Remove Duplicates from Sorted Array.cpp
  C++/Chocolate Distribution Problem.cpp
  C++/Remove Duplicates from Sorted Array.cpp
Labels: Hacktoberfest-Accepted

#17 Problem statement and solution added
  Java/TrappingRainwater.class
  Java/TrappingRainwater.java
Labels: Hacktoberfest-Accepted

#20 Create Subarray Sum Equals K.cpp
  C++/Subarray Sum Equals K.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#24 Leetcode - Search in Rotated Sorted Array
  C++/Search in Rotated Sorted Array.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#23 Longest Substring
  C++/LongestSubstring.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#22 Create CountConnectedComponents_Graphs.cpp
  C++/CountConnectedComponents_Graphs.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#26 leetcode_solutions
  C/Add_Digits.c
  C/Pow_x_n.c
  C/Search_Insert_Position.c
  python/Length_of_Last_Word.py
  python/Power_of_Two.py
  python/Remove_Element.py
  python/Roman_to_integer.py
  python/Squares_of_a_Sorted_Array.py
  python/Two_Sum.py
  python/Valid_Anagram.py
  python/sqrt_x.py
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#25 Majority Vote Java
  Java/MajorityVote.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#28 Created Integer to Roman.cpp
  C++/Integer to Roman.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#29 Added Java Dsa codes
  Java/DoubleLinkedList.java
  Java/LinkedList.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#30 Added a LeetCode Java Problem
  Java/SplitinkedListinParts.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#31 2d array questions added
  C++/CountingBits/CountingBits.cpp
  C++/CountingBits/question output.txt
  C++/addbinary/Addbinary.cpp
  C++/addbinary/question-and-output.txt
  C++/climbingstairs/ClimbingStairs.cpp
  C++/climbingstairs/question_and_output.txt
  C++/find duplicate number/FindDuplicateNumber.cpp
  C++/find duplicate number/question output_.txt
  C++/find index of first occurence of a string/FindingIndexoffirstOccurenceofAString.cpp
  C++/find index of first occurence of a string/question_and_output__.txt
  C++/merge sorted array/MergesortedArray.cpp
  C++/merge sorted array/question_output.txt
  C++/move_zeroes/move Zeroes.cpp
  C++/move_zeroes/question and output.txt
  C++/remove duplicates from sorted array/Remove_Duplicates_from_Sorted_Array.cpp
  C++/remove duplicates from sorted array/question___and_output.txt
  C++/search in rotated sorted array/SearchInRotatedSortedArray.cpp
  C++/search in rotated sorted array/question_and_output___.txt
  C++/spiral matrix/SpiralMatrix.cpp
  C++/spiral matrix/question____and_output.txt
  C++/threesome/Threesome.cpp
  C++/threesome/question_____and_output.txt
  C++/twosum/TwoSum.cpp
  C++/twosum/question__and_output.txt
  C++/valid parenthesis/ValidParenthesis.cpp
  C++/valid parenthesis/question_and__output.txt
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#32 Create Walking Robot Simulation.java
  Java/Walking Robot Simulation.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#33 Added Find Missing Observations
  Find Missing Observations
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#34 3sum
  C++/3sum.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#38 calculator in python
  calculator.ipynb
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#37 Added Dynamic Programming solution to Climbing Stair
  C++/climbingstairs/ClimbingStairs.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#39 Sieve.c
  Sieve.c
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#40 Create creating customhashmap
  Java/creating customhashmap
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#43 Update README.md
  README.md
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#45 added dijkstras algorithm in cpp code
  C++/dijkstra's_algorithm.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#46 Added a code for finding the shortest path
  Java/shortestPathUsing4Directions.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#48 Create LinearSearch.java
  Java/LinearSearch.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#60 Update the PeakindexMountainArray
  C++/PeakIndexMountainArray.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#58 added PalindromeNumber.java
  Java/PalindromeNumber.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#63 Adding ContainerMostWater
  C++/ConatinerWithMostWater.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#65 Leetcode problem [Balance a BST] in java
  Java/Balance a BST.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#56 58-LeetCode
  Java/58-Length of Last Word.java
  Java/590-N-ary Tree Postorder Traversal.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#68 To form binary tree from post and inorder traversal #66
  C++/BinaryTree_from_preorderAndPostorder.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#72 Add files via upload
  .github/ISSUE_TEMPLATE/add-new-project--📚.md
  .github/ISSUE_TEMPLATE/bug-report-🐛.md
  .github/ISSUE_TEMPLATE/code-enhancement-📝-.md
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#73 Create 5-longest_palindromic_substring.java
  Java/5-longest_palindromic_substring.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#70 Create WarehouseOrderOptimizer.cpp
  C++/WarehouseOrderOptimizer.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#78 Create Sieve_Algorithms.cpp
  C++/Sieve_Algorithms.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#88 Create Valid_Number.cpp
  C++/Valid_Number.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#85 Create Kadane's_Algorithm.cpp
  C++/Kadane's_Algorithm.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#99 spiral matrix
  C++/spiral matrix/SpiralMatrix.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#50 Create BubbleSort.java
  Java/BubbleSort.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#104 Added solution to koko eating bananas
  C++/Koko Eating Bananas/Koko_Eating_Banana.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#41 Create customhashmap.java
  Java/customhashmap.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#51 Create SelectionSort.java
  Java/SelectionSort.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#49 Create BinarySearch.java
  Java/BinarySearch.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#82 4Sum.cpp
  C++/4Sum
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#91 Create ValidateBinarySearchTree.py
  python/ValidateBinarySearchTree.py
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#69 Create DynamicRoadNetwork.cpp
  C++/DynamicRoadNetwork.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#100 Create Floyd_Warshall.cpp
  C++/Floyd_Warshall.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#108 Adding Leetcode Problem
  C++/LongestSubstrWithoutRepeatChar.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#98 Added solution to Floyd Warshall Algorithm
  C++/Floyd-Warshall.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#110 Adding dynamic problem with optimized solution.
  C++/House Robber/houserobber.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#113 Create Dutch_National_Flag.cpp
  C++/Dutch_National_Flag.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#116 Add greedy_approch_stock.py file to python folder
  python/greedy_approch_stock.py
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#118 Create Leetcode_2416.cpp
  C++/Leetcode_2416.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#117 implemented_rotate_linkedlist
  C++/Rotate_linked_list.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#120 solving the House Robber Problem using memoization
  Java/HouseRobber.java
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#124 feat (#123): Add solution for the Two Sum problem using JS
  JavaScript/two-sum.js
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#119 Added solution to Kth largest sum in a Binary tree problem
  C++/kth largest sum in a Binary tree/kth_largest_sum_bt.cpp
Labels: documentation, Hacktoberfest-Accepted, Hacktoberfest-2024

#126 Create sum_of_three.py
  python/sum_of_three.py
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#136 Added Palindrome solution to Python
  python/palindrome.py
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#141 Moore's voting algo , q- element that appered more than n/2 time
  C++/moore's voting algo.cpp
Labels: good first issue, Hacktoberfest-2024

#142 Add solution to: Count Odd Numbers in an Interval Range
  C++/Count Odd Numbers in an Interval Range.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#129 Reverse Pairs. [493]
  C++/ReversePairs
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#143 Added Valid Parantheses solution to python folder
  python/valid_parentheses.py
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#151 Efficient Solution for Network Delay Time Problem Using Dijkstra's Algorithm in C++
  C++/Network Delay Time/Network Delay Time.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#158 Added Solution to Palindrome_Partitioning
  C++/Palindrome_Partitioning.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#154 Create Searcha2DMatrix.cpp
  C++/Searcha2DMatrix.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#161 Added move_zeros_to_end in python
  python/move_zeros_to_end.py
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#156 Add longest square streak
  C++/Longest Square Streak in an Array/LongestSquareStreakInAnArray.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#155 Added solution to Count Square Submatrices with All Ones
  C++/Count Square Submatrices with All Ones/CountSquareSubmatricesWithAllOnes.cpp
Labels: enhancement

#172 added a question 'rearrange by sign pairs'
  python/rearrange_by_sign.py
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#170 Find missing number from array in python
  python/find_missing_number.py
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#165 Rotten Oranges added in C++.
  C++/Rotten Oranges/rottenOrangesSol.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#159 Add : Contains Duplicate
  C++/Contains Duplicate.cpp
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024

#74 Added Longest Common Subsequence solution to C++ folder
  C++/LongestCommonSubsequence.cpp
Labels: good first issue, Hacktoberfest-Accepted, Hacktoberfest-2024

#122 Created a code for Merge Sort
  Java/MergeSort.java
Labels: Hacktoberfest-Accepted, Hacktoberfest-2024
